### ISSUE TITLE
Map more instruments for Bitmex

### ISSUE THREAD

**Issue by atemerev** [spawnproc/ticker#2]
Add the following instruments for Bitmex (all of them are futures or swaps, so currency pair naming conventions do not apply).

COIN_BH17
DASH7D
ETH7D
XBTUSD

(futures have changing symbols, so they are to be handled separately)

In our storage, they are to be mapped as is with '@BitMEX' added as exchange designator, e.g.

COIN_BH17@BitMEX
DASH7D@BitMEX
ETH7D@BitMEX
XBTUSD@BitMEX

**Comment by 5HT** [comment]
If they are `swaps` or even `butterflies` could we name it just like that or create the proper in-house naming?

**Comment by atemerev** [comment]
There is one (ugly, but universal). Looks like <LP>:<asset_class>:<instrument_type>:<designator>:<symbol>:<contract_currency>, e.g.

BitMEX:crypto:swap:XBTUSD:USD
BitMEX:crypto:future:ETH7D:USD
GDAX:crypto:spot:BTC/EUR:EUR

looks ugly, need to think more
